name: Deploy GitBook based on GitHub Actions

on:
  push:
    branches: [main, task/github-actions]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Setup gitbook-cli
        run: |
          npm install -g gitbook-cli
          cd $(npm root -g)/gitbook-cli/node_modules/npm
          npm install graceful-fs@4.1.4

      - name: Deploy gitbook
        run: npm run deploy
